### ISSUE TITLE
Unread notifications

### ISSUE THREAD

**Issue by bykbyk301** [comewithgeul/comewithgeul#96]
![image](https://user-images.githubusercontent.com/16695846/107361195-51c32f80-6b1a-11eb-8950-3dc2a54f9054.jpeg)

Although I already read all the notifications in the previous table, when I created a new one the notification panel changed from read > unread status. When I open the panel, notifications I "read" appear as "unread" again.

**Comment by afkim14** [comment]
This is indeed confusing but it's correct by our design 😅 ...

We currently display different notifications when the room has started and not (reference: https://docs.google.com/document/d/1bcnVRdtBlot96vmjM7eOvcRvkSHk2SUf1F9sfw-d_pc/edit). So what's most likely happening is that you read all the "started room" notifications, but not the "not started room" ones. So when you create a new room, those notifications show up as unread since technically they are unread.

**Comment by afkim14** [comment]
Changed so that we display all notifications regardless of room state.

Relevant commit: 0c0e99aea87f06cb918973840d964a58bdc8f835
